### ISSUE TITLE
Required Properties should be applied to models' type (but not)

### ISSUE THREAD

**Issue by yasaichi** [microsoft/kiota-typescript#1101]
Thanks for working on the great libary! Recently I have finished [the quick start tutorial](https://learn.microsoft.com/en-us/openapi/kiota/quickstarts/typescript) and found that the generated code for models doesn't follow OpenAPI specification.

# Repro steps

1. Change the properties of `post` component in [this example](https://learn.microsoft.com/en-us/openapi/kiota/quickstarts/typescript#generate-the-api-client) to `required` ones:

```yaml
components:
  schemas:
    post:
      type: object
      properties:
        userId:
          type: integer
        id:
          type: integer
        title:
          type: string
        body:
          type: string
      required:
        - userId
        - id
        - title
        - body
```

2. Run the following command:

```bash
$ kiota --version
1.12.0+1735a2ff916ebec661974d9560f1dd00d3dc349b

$ kiota generate --co -l typescript -d posts-api.yml -c PostsClient -o ./client 
```

# Expectated code

```ts
// client/models/index.ts
export interface Post extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The body property
     */
    body: string;
    /**
     * The id property
     */
    id: number;
    /**
     * The title property
     */
    title: string;
    /**
     * The userId property
     */
    userId: number;
}
```

# Actual code

```ts
// client/models/index.ts
export interface Post extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The body property
     */
    body?: string;
    /**
     * The id property
     */
    id?: number;
    /**
     * The title property
     */
    title?: string;
    /**
     * The userId property
     */
    userId?: number;
}
```
