### ISSUE TITLE
[BUG]: Kiota fails to deserialize response when it contains array of enums

### ISSUE THREAD

**Issue by salmannotkhan** [microsoft/kiota-typescript#744]
Kiota fails to de-serialize the response when it contains this array field of enum in OpenAPI:

```yaml
xyz:
  type: array
  items:
    type: string
    enum:
      - foo
      - bar
      - baz
```

It generates code like this:
```js
"xyz": n => { instance.xyz = n.getEnumValues(xyz); }
```

It calls [getEnumValues method](https://github.com/microsoft/kiota-typescript/blob/main/packages/serialization/json/src/jsonParseNode.ts#L94-L100) of @microsoft/kiota-serialization-json package

and it errors on

```ts
return rawValues.split(",").map((x) => type[toFirstCharacterUpper(x)] as T);
//              ^ Here, as the rawValues is already an array and array doesn't have split method
```
